###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    postgres:
      image: postgres:9.6-alpine
      container_name: iw-php-service-postgres
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - POSTGRES_USER=iw-php
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=iw-php

    elasticsearch:
      image: elasticsearch:5.4-alpine
      container_name: iw-php-service-elasticsearch

    webserver:
      env_file: ./project-vars.env
      image: nginx:alpine
      container_name: iw-php-service-webserver
      working_dir: /application/$PROJECT_NAME
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      env_file: ./project-vars.env
      build: phpdocker/php-fpm
      container_name: iw-php-service-php-fpm
      working_dir: /application
      volumes:
        - .:/application/$PROJECT_NAME
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php7/conf.d/99-overrides.ini

